name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)


trigger:
  - notes

stages:  

  - stage: generate_notes
    jobs:
      - job:
        displayName: generate notes
        steps:
          - task: GenerateReleaseNotes@0
            inputs:
              FromBuildId: "$(Build.BuildId)"
              ToBuildId: "8bd7ba7c"
              ReleaseNotesPath: "GeneratedNotes"
              ReleaseNotesFile: "ReleaseNotes.md"
              AdditionalNote: '**Build Number: $(Build.BuildId)**'
              Test: false

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "/home/vsts/work/1/s/GeneratedNotes/"
              artifact: "notes"
              publishLocation: "pipeline"
